Repository witseie-elen4010/2022-group-lab-012, pull requests merged in 2022-06, with the labels that each got.

#32 Time and game mode options.
  .github/workflows/timing-options-implementation_webwordle.yml
  app.js
  public/Lobby.html
  public/account.html
  public/index.html
  public/instructions.html
  public/javascripts/LobbyHandle.js
  public/javascripts/ModeButtons.js
  public/javascripts/Timer.js
  public/javascripts/ToggleButton.js
  public/stylesheets/style.css
  public/welcome.html
  routes/index.js
Labels: developer-sized-story, user-story, UI layer, Services/Logic layer

#51 play page bugs fixed
  public/play.html
  public/stylesheets/play.css
Labels: bug

#56 Remove time options
  app.js
  public/javascripts/ModeButtons.js
  public/javascripts/ToggleButton.js
  public/play.html
  public/playUntimed.html
  public/stylesheets/style.css
  public/welcome.html
  routes/index.js
Labels: wontfix

#58 deployment-fix3
  package.json
Labels: bug

#59 deployment-fix4
  package.json
Labels: bug

#60 Changed port for deployment
  app.js
Labels: bug

#61 Setting up tests
  package-lock.json
  package.json
  public/__tests__/TestFunctions.spec.js
  public/javascripts/TestFunctions.js
Labels: developer-sized-story
